name: Deploy CloudForge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2
        
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          command_timeout: 10m
          script: |
            if [ ! -d "cloudforge" ]; then
              git clone https://github.com/Birarvindersingh/cloudforge.git
            fi
            
            cd cloudforge
            git pull
            
            if [ ! -d "venv" ]; then
              python3 -m venv venv
            fi
            
            source venv/bin/activate
            
            pip install --upgrade pip setuptools wheel
            pip install -r requirements.txt --no-cache-dir
            
            sudo bash -c 'cat <<EOF > /etc/systemd/system/cloudforge.service
            [Unit]
            Description=CloudForge FastAPI Server
            After=network.target

            [Service]
            User=ubuntu
            WorkingDirectory=/home/ubuntu/cloudforge
            ExecStart=/home/ubuntu/cloudforge/venv/bin/uvicorn app.main:app --host 0.0.0.0 --port 8000
            Restart=always

            [Install]
            WantedBy=multi-user.target
            EOF'
            
            sudo systemctl daemon-reload
            sudo systemctl enable cloudforge
            sudo systemctl restart cloudforge